# mailer.py
# Sends roadmap PDF to user's email via Gmail SMTP.
#
# Setup (one time):
#   1. Go to https://myaccount.google.com/apppasswords
#   2. Select app: Mail, device: Windows/Mac
#   3. Copy the 16-character App Password
#   4. Add to your .env file:
#      MAIL_EMAIL=your_gmail@gmail.com
#      MAIL_PASSWORD=xxxx xxxx xxxx xxxx

import os
import io
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from email.mime.base      import MIMEBase
from email               import encoders
from dotenv              import load_dotenv

load_dotenv()

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587


def _build_html_body(roadmap: dict, username: str) -> str:
    """Nice HTML email body."""
    skills_html = ""
    for skill in roadmap.get("skills", []):
        topics = ", ".join(skill.get("topics", []))
        skills_html += f"""
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;font-weight:500;color:#111827">{skill['name']}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#6B7280">{skill.get('duration','')}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #E5E7EB;color:#6B7280;font-size:13px">{topics}</td>
        </tr>"""

    level_colors = {
        "beginner":     "#1D9E75",
        "intermediate": "#7F77DD",
        "advanced":     "#D85A30",
    }
    level_color = level_colors.get(roadmap.get("level", "").lower(), "#7F77DD")

    return f"""
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#F9F9FB;font-family:'Segoe UI',Arial,sans-serif">
  <div style="max-width:600px;margin:32px auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,0.08)">

    <!-- Header -->
    <div style="background:linear-gradient(135deg,#3C3489 0%,#7F77DD 100%);padding:32px 36px">
      <div style="font-size:13px;color:rgba(255,255,255,0.7);margin-bottom:6px">✦ PathForge AI</div>
      <h1 style="margin:0;font-size:24px;font-weight:800;color:#ffffff;letter-spacing:-0.5px">
        Your Roadmap is Ready!
      </h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,0.8);font-size:14px">
        Hi {username}, your personalized career roadmap has been generated.
      </p>
    </div>

    <!-- Roadmap summary -->
    <div style="padding:28px 36px">
      <h2 style="margin:0 0 4px;font-size:20px;font-weight:700;color:#111827">{roadmap.get('goal','')}</h2>
      <div style="display:flex;gap:8px;margin:10px 0 20px;flex-wrap:wrap">
        <span style="background:{level_color}22;color:{level_color};padding:3px 12px;border-radius:20px;font-size:12px;font-weight:600">{roadmap.get('level','')}</span>
        <span style="background:#F3F4F6;color:#6B7280;padding:3px 12px;border-radius:20px;font-size:12px">⏱ {roadmap.get('duration','')}</span>
        <span style="background:#F3F4F6;color:#6B7280;padding:3px 12px;border-radius:20px;font-size:12px">📚 {roadmap.get('hours_per_day','')} hrs/day</span>
        <span style="background:#F3F4F6;color:#6B7280;padding:3px 12px;border-radius:20px;font-size:12px">🎯 {len(roadmap.get('skills',[]))} skills</span>
      </div>

      <!-- Skills table -->
      <h3 style="font-size:14px;font-weight:600;color:#374151;margin:0 0 10px;text-transform:uppercase;letter-spacing:0.5px">Skills in this Roadmap</h3>
      <table style="width:100%;border-collapse:collapse;border:1px solid #E5E7EB;border-radius:10px;overflow:hidden">
        <thead>
          <tr style="background:#F9F9FB">
            <th style="padding:8px 12px;text-align:left;font-size:12px;color:#6B7280;font-weight:600;text-transform:uppercase">Skill</th>
            <th style="padding:8px 12px;text-align:left;font-size:12px;color:#6B7280;font-weight:600;text-transform:uppercase">Duration</th>
            <th style="padding:8px 12px;text-align:left;font-size:12px;color:#6B7280;font-weight:600;text-transform:uppercase">Topics</th>
          </tr>
        </thead>
        <tbody>
          {skills_html}
        </tbody>
      </table>

      <!-- CTA -->
      <div style="margin-top:24px;padding:16px;background:#EEEDFE;border-radius:12px;text-align:center">
        <p style="margin:0 0 12px;font-size:14px;color:#3C3489;font-weight:500">
          📎 Your full roadmap PDF is attached to this email.
        </p>
        <p style="margin:0;font-size:13px;color:#534AB7">
          Open the app to start tracking your progress skill by skill.
        </p>
      </div>
    </div>

    <!-- Footer -->
    <div style="padding:16px 36px;background:#F9F9FB;border-top:1px solid #E5E7EB;text-align:center">
      <p style="margin:0;font-size:12px;color:#9CA3AF">
        Generated by PathForge AI · Your personalized career roadmap generator
      </p>
    </div>

  </div>
</body>
</html>"""


def send_roadmap_email(to_email: str, username: str, roadmap: dict, pdf_bytes: bytes) -> dict:
    """
    Send the roadmap PDF to the user's email.

    Args:
        to_email   : recipient email address
        username   : user's display name
        roadmap    : roadmap dict (goal, level, skills etc.)
        pdf_bytes  : PDF file as bytes (from ai_generator.generate_pdf_bytes)

    Returns:
        {"success": True} or {"success": False, "error": "..."}
    """
    sender_email    = os.environ.get("MAIL_EMAIL", "").strip()
    sender_password = os.environ.get("MAIL_PASSWORD", "").strip()

    if not sender_email or not sender_password:
        return {
            "success": False,
            "error": "MAIL_EMAIL or MAIL_PASSWORD missing in .env file."
        }

    # ── Build email ──
    msg = MIMEMultipart("alternative")
    msg["From"]    = f"PathForge AI <{sender_email}>"
    msg["To"]      = to_email
    msg["Subject"] = f"✦ Your {roadmap.get('goal', 'Career')} Roadmap — PathForge AI"

    # Plain text fallback
    plain = (
        f"Hi {username},\n\n"
        f"Your {roadmap.get('goal')} roadmap ({roadmap.get('level')}) is ready!\n"
        f"Duration: {roadmap.get('duration')} | {roadmap.get('hours_per_day')} hrs/day\n\n"
        f"Skills covered:\n"
        + "\n".join(f"  • {s['name']}" for s in roadmap.get("skills", []))
        + "\n\nThe full PDF is attached.\n\n— PathForge AI"
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_html_body(roadmap, username), "html"))

    # ── Attach PDF ──
    filename = f"{roadmap.get('goal','Roadmap').replace(' ','_')}_Roadmap.pdf"
    part = MIMEBase("application", "octet-stream")
    part.set_payload(pdf_bytes)
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f'attachment; filename="{filename}"')
    msg.attach(part)

    # ── Send via Gmail SMTP ──
    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, to_email, msg.as_string())
        print(f"[Mailer] Email sent to {to_email} for '{roadmap.get('goal')}'")
        return {"success": True}
    except smtplib.SMTPAuthenticationError:
        return {
            "success": False,
            "error": (
                "Gmail authentication failed. "
                "Make sure you used an App Password, not your regular Gmail password. "
                "Get one at: https://myaccount.google.com/apppasswords"
            )
        }
    except smtplib.SMTPException as e:
        return {"success": False, "error": f"SMTP error: {e}"}
    except Exception as e:
        return {"success": False, "error": str(e)}